# ================================
# kohub 프로덕션 환경
# 
# 사용법:
#   1. kecp-sso 먼저 실행 (권장) 또는 내장 Keycloak 사용
#   2. podman-compose -f compose.prod.yml up -d
# ================================

services:
  # PostgreSQL 데이터베이스
  db:
    image: docker.io/postgres:16-alpine
    container_name: kohub-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - kohub-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - kohub-network

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kohub-backend
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-sso}
      # Database
      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      # Keycloak SSO
      KEYCLOAK_URL: ${KEYCLOAK_URL:-http://keycloak:8080}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      # CORS
      CORS_ORIGINS: ${CORS_ORIGINS}
      # Adapters
      UPTIME_KUMA_ENABLED: ${UPTIME_KUMA_ENABLED:-true}
      UPTIME_KUMA_URL: ${UPTIME_KUMA_URL}
      TERMIX_ENABLED: ${TERMIX_ENABLED:-true}
      TERMIX_URL: ${TERMIX_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - kohub-network
      - kecp-sso-network

  # React Frontend (프로덕션 빌드)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-/api/v1}
        VITE_SSO_ENABLED: ${VITE_SSO_ENABLED:-true}
        VITE_KEYCLOAK_URL: ${VITE_KEYCLOAK_URL}
        VITE_KEYCLOAK_REALM: ${VITE_KEYCLOAK_REALM:-k-ecp}
        VITE_KEYCLOAK_CLIENT_ID: ${VITE_KEYCLOAK_CLIENT_ID:-k-ecp-kohub}
    container_name: kohub-frontend
    depends_on:
      - backend
    restart: always
    networks:
      - kohub-network

  # Nginx Reverse Proxy
  nginx:
    image: docker.io/nginx:alpine
    container_name: kohub-nginx
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - kohub-network

volumes:
  kohub-db-data:

networks:
  kohub-network:
    driver: bridge
  # kecp-sso 네트워크 (외부)
  kecp-sso-network:
    external: true
    name: kecp-sso_kecp-sso-network
